// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-YIehOmEj9GxxKAzU1kVxdTGWGslxFSY',
    appId: '1:231393387344:web:42db6e1e64ceb3efee8255',
    messagingSenderId: '231393387344',
    projectId: 'apna-blog-e68ef',
    authDomain: 'apna-blog-e68ef.firebaseapp.com',
    storageBucket: 'apna-blog-e68ef.firebasestorage.app',
    measurementId: 'G-3K3V9WCSS9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw5f3TcaYe781i5zsW-OhbYRSrvg5wQk0',
    appId: '1:231393387344:android:997921cb586a8ea0ee8255',
    messagingSenderId: '231393387344',
    projectId: 'apna-blog-e68ef',
    storageBucket: 'apna-blog-e68ef.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTqj78Q-2vxUPZTUmVPWMsPw8rGamRntQ',
    appId: '1:231393387344:ios:0ea850f64746281bee8255',
    messagingSenderId: '231393387344',
    projectId: 'apna-blog-e68ef',
    storageBucket: 'apna-blog-e68ef.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTqj78Q-2vxUPZTUmVPWMsPw8rGamRntQ',
    appId: '1:231393387344:ios:0ea850f64746281bee8255',
    messagingSenderId: '231393387344',
    projectId: 'apna-blog-e68ef',
    storageBucket: 'apna-blog-e68ef.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-YIehOmEj9GxxKAzU1kVxdTGWGslxFSY',
    appId: '1:231393387344:web:9471eaf3c0300fccee8255',
    messagingSenderId: '231393387344',
    projectId: 'apna-blog-e68ef',
    authDomain: 'apna-blog-e68ef.firebaseapp.com',
    storageBucket: 'apna-blog-e68ef.firebasestorage.app',
    measurementId: 'G-TKTVQVR0LM',
  );
}
